# Generated by Django 4.0.4 on 2022-04-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
